### ISSUE TITLE
Scoreboard list glitches out if server is in teamplay mode

### ISSUE THREAD

**Issue by aWhhdGVteXNlbGY** [Troll338cz/source-sdk-2013-hl1dm#3]
[redacted]

**Comment by Troll338cz** [comment]
Well, HL1MP never had functioning team system.
If you just want to restore scoreboard rendering then in hl1_clientscoreboard.cpp uncomment lines 371 and 372 and it should work again.
![image](https://github.com/user-attachments/assets/a864bff9-0280-4557-8e66-5c364bd18ef4)
It's not possible to fix teamplay and spectators without some hard work and it would require all clients to change their files for it to work
